services:
  tg_accessbot_app:
    build: .
    env_file: .env
    depends_on:
      - postgres
      - mongodb
    volumes:
      - .:/app

  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
  
  mongodb:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/var/lib/mongodb/data

volumes:
  postgres_data:
  mongodb_data:
