services:
  tg_accessbot_app:
    build: .
    env_file: .env
    depends_on:
      - postgres
      - mongodb
    command: alembic upgrade head 
    command: python src/main.py
    volumes:
      - .:/app

  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
  
  mongodb:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    env_file: .env
  
  ollama:
    image: ollama/ollama
    container_name: ollama
    depends_on:
      - tg_accessbot_app
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./Modelfile:/Modelfile
    entrypoint: ["/bin/sh", "-c", "ollama create accessbot_model -f /Modelfile & sleep 5 && ollama serve"]  

volumes:
  postgres_data:
  mongodb_data:
  ollama_data:
