name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 34.172.18.169
          username: actions
          key: ${{ secrets.ID_RSA }}
          script: |
            cd /home/justphanta1313/tg_AI_accessbot/
            git pull
            docker-compose down
            docker-compose up -d --build
